In [2]:
%matplotlib inline
import torch
from IPython import display
from matplotlib import pyplot as plt
import numpy as np
import random

print(torch.__version__)

1.4.0+cu92


# pytorch 相关

In [2]:
x= torch.empty(5,3)
print(x)

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])


In [5]:
x=torch.rand(5,3)    # 均匀分布
x

tensor([[0.5666, 0.4262, 0.5053],
        [0.5166, 0.5501, 0.1567],
        [0.3099, 0.2343, 0.9521],
        [0.5727, 0.9070, 0.9087],
        [0.3597, 0.3538, 0.2512]])

In [7]:
x=torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x=torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [9]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)
x=torch.randn_like(x,dtype=torch.float)    # randn标准正态分布
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.0323, -0.7425,  2.0079],
        [-0.8669,  1.0570,  1.3291],
        [ 1.3519, -1.0387, -1.5253],
        [ 0.3632,  0.2290, -0.6939],
        [ 0.4800, -0.0284,  0.7228]])


In [10]:
print(x.size())

torch.Size([5, 3])


## 运算

In [11]:
y = torch.rand(5, 3)
x+y

tensor([[-1.3489, -0.7124,  2.7430],
        [-0.4472,  1.9642,  1.4694],
        [ 1.9832, -0.2676, -0.8374],
        [ 0.7799,  1.1130,  0.2370],
        [ 0.5072,  0.9633,  1.1153]])

In [12]:
torch.add(x,y)

tensor([[-1.3489, -0.7124,  2.7430],
        [-0.4472,  1.9642,  1.4694],
        [ 1.9832, -0.2676, -0.8374],
        [ 0.7799,  1.1130,  0.2370],
        [ 0.5072,  0.9633,  1.1153]])

In [13]:
result=torch.empty(5,3)
torch.add(x,y,out=result)

tensor([[-1.3489, -0.7124,  2.7430],
        [-0.4472,  1.9642,  1.4694],
        [ 1.9832, -0.2676, -0.8374],
        [ 0.7799,  1.1130,  0.2370],
        [ 0.5072,  0.9633,  1.1153]])

In [15]:
#任何 以``_`` 结尾的操作都会用结果替换原变量. 例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.
y.add_(x)

tensor([[-1.3489, -0.7124,  2.7430],
        [-0.4472,  1.9642,  1.4694],
        [ 1.9832, -0.2676, -0.8374],
        [ 0.7799,  1.1130,  0.2370],
        [ 0.5072,  0.9633,  1.1153]])

In [22]:
print(x[:,1])

tensor([-0.7425,  1.0570, -1.0387,  0.2290, -0.0284])


In [18]:
x

tensor([[-2.0323, -0.7425,  2.0079],
        [-0.8669,  1.0570,  1.3291],
        [ 1.3519, -1.0387, -1.5253],
        [ 0.3632,  0.2290, -0.6939],
        [ 0.4800, -0.0284,  0.7228]])

In [23]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
x = torch.randn(1)
print(x)
print(x.item())    #只有一个元素的张量，使用.item()来得到Python数据类型的数值

tensor([0.0286])
0.028576958924531937


## numpy转换

In [27]:
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [28]:
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [29]:
#Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
import numpy as np
c=np.ones(5)
d=torch.from_numpy(c)
print(c)
print(d)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [34]:
np.add(c,1,out=c)
print(c)
print(d)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA张量

In [37]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改

tensor([1.0286], device='cuda:0')
tensor([1.0286], dtype=torch.float64)


In [42]:
x=torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [44]:
y=x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [45]:
z=y*y*3
out=z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [46]:
#.requires_grad_( ... ) 可以改变现有张量的 requires_grad属性。 如果没有指定的话，默认输入的flag是 False
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## 梯度

In [48]:
out.backward()

In [49]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [62]:
x = torch.randn(3, requires_grad=True)
y = x * 2

while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-703.3149, -409.6426, -743.9744], grad_fn=<MulBackward0>)


In [67]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [68]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


# 线性回归相关

In [3]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)  # random read 10 samples
    for i in range(0, num_examples, batch_size):
        j = torch.LongTensor(indices[i: min(i + batch_size, num_examples)]) # the last time may be not enough for a whole batch
        yield  features.index_select(0, j), labels.index_select(0, j)

In [7]:
# set input feature number 
num_inputs = 2
# set example number
num_examples = 1000
# set true weight and bias in order to generate corresponded label
true_w = [2, -3.4]
true_b = 4.2

features = torch.randn(num_examples, num_inputs,
                      dtype=torch.float32)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()),
                       dtype=torch.float32)

batch_size = 10
for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break

tensor([[ 0.3631,  2.3438],
        [-0.1073,  0.0760],
        [ 1.4536, -0.4399],
        [ 0.8193, -1.5367],
        [-0.3358, -1.6542],
        [ 0.3134,  2.0116],
        [-0.3792, -0.8853],
        [ 0.4347, -0.6015],
        [ 1.6026,  0.4230],
        [ 0.3328, -0.0355]]) 
 tensor([-3.0300,  3.7372,  8.6126, 11.0828,  9.1893, -2.0101,  6.4600,  7.1174,
         5.9585,  4.9923])


# softmax与分类模型相关

softmax:
直接使用输出层的输出有两个问题：
一方面，由于输出层的输出值的范围不确定，我们难以直观上判断这些值的意义。例如，刚才举的例子中的输出值10表示“很置信”图像类别为猫，因为该输出值是其他两类的输出值的100倍。但如果o1=o3=103，那么输出值10却又表示图像类别为猫的概率很低。
另一方面，由于真实标签是离散值，这些离散值与不确定范围的输出值之间的误差难以衡量。

交叉熵函数：衡量两个概率分布差异的测量函数，只关心对正确类别的预测概率，因为只要其值足够大，就可以确保分类结果正确。

In [8]:
def softmax(X):
    X_exp = X.exp()
    partition = X_exp.sum(dim=1, keepdim=True)
    # print("X size is ", X_exp.size())
    # print("partition size is ", partition, partition.size())
    return X_exp / partition  # 这里应用了广播机制

## 多层感知机相关

激活函数：ReLU、Sigmoid、tanh

In [9]:
#定义模型参数

num_inputs, num_outputs, num_hiddens = 784, 10, 256

W1 = torch.tensor(np.random.normal(0, 0.01, (num_inputs, num_hiddens)), dtype=torch.float)
b1 = torch.zeros(num_hiddens, dtype=torch.float)
W2 = torch.tensor(np.random.normal(0, 0.01, (num_hiddens, num_outputs)), dtype=torch.float)
b2 = torch.zeros(num_outputs, dtype=torch.float)

params = [W1, b1, W2, b2]
for param in params:
    param.requires_grad_(requires_grad=True)

In [10]:
def relu(X):
    return torch.max(input=X, other=torch.tensor(0.0))

In [11]:
def net(X):
    X = X.view((-1, num_inputs))
    H = relu(torch.matmul(X, W1) + b1)
    return torch.matmul(H, W2) + b2

In [12]:
loss=torch.nn.CrossEntropyLoss()

In [16]:
def train_ch3(net, train_iter, test_iter, loss, num_epochs, batch_size,
               params=None, lr=None, optimizer=None):
    for epoch in range(num_epochs):
        train_l_sum, train_acc_sum, n = 0.0, 0.0, 0
        for X, y in train_iter:
            y_hat = net(X)
            l = loss(y_hat, y).sum()

            # 梯度清零
            if optimizer is not None:
                optimizer.zero_grad()
            elif params is not None and params[0].grad is not None:
                for param in params:
                    param.grad.data.zero_()

            l.backward()
            if optimizer is None:
                d2l.sgd(params, lr, batch_size)
            else:
                optimizer.step()  # “softmax回归的简洁实现”一节将用到


            train_l_sum += l.item()
            train_acc_sum += (y_hat.argmax(dim=1) == y).sum().item()
            n += y.shape[0]
        test_acc = evaluate_accuracy(test_iter, net)
        print('epoch %d, loss %.4f, train acc %.3f, test acc %.3f'
           % (epoch + 1, train_l_sum / n, train_acc_sum / n, test_acc))


## 文本预处理、语言模型相关

1.读入文本
2.分词
3.建立字典，将每个词映射到一个唯一的索引（index）
4.将文本从词的序列转换为索引的序列，方便输入模型

n元语法，基于n-1阶马尔科夫链的概率语言模型
缺陷：参数空间过大、数据稀疏

相邻采样：相邻的两个随机小批量在原始序列上的位置相毗邻
随机采样：在随机采样中，每个样本是原始序列上任意截取的一段序列，相邻的两个随机小批量在原始序列上的位置不一定相毗邻

## 循环神经网络相关

In [20]:
def one_hot(x, n_class, dtype=torch.float32):
    result = torch.zeros(x.shape[0], n_class, dtype=dtype, device=x.device)  # shape: (n, n_class)
    result.scatter_(1, x.long().view(-1, 1), 1)  # result[i, x[i, 0]] = 1
    return result

In [21]:
x=torch.tensor([0,2])
x_one_hot=one_hot(x,1027)
print(x_one_hot)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.]])


In [22]:
x_one_hot.shape

torch.Size([2, 1027])

In [27]:
x.long().view(-1,1)

tensor([[0],
        [2]])

In [28]:
# 梯度裁剪
def grad_clipping(params, theta, device):
    norm = torch.tensor([0.0], device=device)
    for param in params:
        norm += (param.grad.data ** 2).sum()
    norm = norm.sqrt().item()
    if norm > theta:
        for param in params:
            param.grad.data *= (theta / norm)

我们通常使用困惑度（perplexity）来评价语言模型的好坏。回忆一下“softmax回归”一节中交叉熵损失函数的定义。困惑度是对交叉熵损失函数做指数运算后得到的值。特别地，
最佳情况下，模型总是把标签类别的概率预测为1，此时困惑度为1；
最坏情况下，模型总是把标签类别的概率预测为0，此时困惑度为正无穷；
基线情况下，模型总是预测所有类别的概率都相同，此时困惑度为类别个数。
显然，任何一个有效模型的困惑度必须小于类别个数。在本例中，困惑度必须小于词典大小vocab_size。